apiVersion: v1
kind: Service
metadata:
  name: back-end
spec:
 type: ClusterIP
 ports:
  - targetPort: 80 # is the port where the backend is exposed
    port: 80  # is the port where service is exposed
 selector:
   app: myapp
   type: back-end

